default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: estate_me_development
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  host: db

test:
  <<: *default
  database: estate_me_test
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  host: db

production:
  <<: *default
  database: estate_me_production
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
